;;; lean4-input.el --- The Lean input method (based/copied from Agda) -*- lexical-binding: t; -*-

;; Copyright (C) 2014 Microsoft Corporation. All rights reserved.
;; Copyright (C) 2024 Free Software Foundation, Inc.

;; Maintainer: Mekeor Melire <mekeor@posteo.de>
;; SPDX-License-Identifier: Apache-2.0, GPL-3.0-or-later

;; This file is not part of GNU Emacs.

;; Some parts of this source code are licensed under Apache-2.0,
;; others are licensed under GNU General Public License version 3 or
;; later.

;;; Commentary:

;; A highly customisable input method which can inherit from other.

;; Quail input methods.  By default the input method is geared towards
;; the input of mathematical and other symbols in Lean programs.
;;
;; Use M-x customize-group lean4-input to customise this input method.
;; Note that the functions defined under "Functions used to tweak
;; translation pairs" below can be used to tweak both the key
;; translations inherited from other input methods as well as the
;; ones added specifically for this one.
;;
;; Use lean4-input-show-translations to see all the characters which
;; can be typed using this input method (except for those
;; corresponding to ASCII characters).

;;; Code:

(require 'cl-lib)
(require 'map)
(require 'quail)
(require 'subr-x)

;; Quail is quite stateful, so be careful when editing this code.
;; Note that with-temp-buffer is used below whenever buffer-local
;; state is modified.

;;;; Utility functions

(defun lean4-input-concat-map (f xs)
  "Concat (map F XS)."
  (apply #'append (mapcar f xs)))

(defun lean4-input-to-string-list (s)
  "Convert a string S to a list of one-character strings.
First remove all space and newline characters."
  (lean4-input-concat-map
   (lambda (c) (if (member c (string-to-list " \n"))
              nil
            (list (string c))))
   (string-to-list s)))

(defun lean4-input-character-range (from to)
  "A string consisting of the characters from FROM to TO."
  (let (seq)
    (dotimes (i (1+ (- to from)))
      (setq seq (cons (+ from i) seq)))
    (concat (nreverse seq))))

;;;; Functions used to tweak translation pairs

(defun lean4-input-compose (f g)
  "\\x -> concatMap F (G x)."
  (lambda (x) (lean4-input-concat-map f (funcall g x))))

(defun lean4-input-or (f g)
  "\\x -> F x ++ G x."
  (lambda (x) (append (funcall f x) (funcall g x))))

(defun lean4-input-nonempty ()
  "Only keep pairs with a non-empty first component."
  (lambda (x) (if (> (length (car x)) 0) (list x))))

(defun lean4-input-prepend (prefix)
  "Prepend PREFIX to all key sequences."
    (lambda (x) `((,(concat prefix (car x)) . ,(cdr x)))))

(defun lean4-input-prefix (prefix)
  "Only keep pairs whose key sequence starts with PREFIX."
  (lambda (x)
    (if (equal (substring (car x) 0 (length prefix)) prefix)
        (list x))))

(defun lean4-input-suffix (suffix)
  "Only keep pairs whose key sequence ends with SUFFIX."
  (lambda (x)
    (if (equal (substring (car x)
                          (- (length (car x)) (length suffix)))
               suffix)
        (list x))))

(defun lean4-input-drop (ss)
  "Drop pairs matching one of the given key sequences.
SS should be a list of strings."
  (lambda (x) (unless (member (car x) ss) (list x))))

(defun lean4-input-drop-beginning (n)
  "Drop N characters from the beginning of each key sequence."
  (lambda (x) `((,(substring (car x) n) . ,(cdr x)))))

(defun lean4-input-drop-end (n)
  "Drop N characters from the end of each key sequence."
  (lambda (x)
    `((,(substring (car x) 0 (- (length (car x)) n)) .
       ,(cdr x)))))

(defun lean4-input-drop-prefix (prefix)
  "Only keep pairs whose key sequence starts with PREFIX.
This prefix is dropped."
  (lean4-input-compose
   (lean4-input-drop-beginning (length prefix))
   (lean4-input-prefix prefix)))

(defun lean4-input-drop-suffix (suffix)
  "Only keep pairs whose key sequence ends with SUFFIX.
This suffix is dropped."
  (lean4-input-compose
   (lean4-input-drop-end (length suffix))
   (lean4-input-suffix suffix)))

;;;; Customization

;; The `:set' keyword is set to
;; `lean4-input-incorporate-changed-setting' so that the input method
;; gets updated immediately when users customize it. However, the
;; setup functions cannot be run before all variables have been
;; defined. Hence the `:initialize' keyword is set to
;; `custom-initialize-default' to ensure that the setup is not
;; performed until `lean4-input-setup' is called at the end of this
;; file.

(defgroup lean4-input nil
  "The Lean input method.
After tweaking these settings you may want to inspect the resulting
translations using `lean4-input-show-translations'."
  :group 'lean
  :group 'leim)

(defcustom lean4-input-inherit
  `(("TeX" . (lean4-input-compose
              (lean4-input-drop '("geq" "leq" "bullet" "qed" "par"))
              (lean4-input-or
               (lean4-input-drop-prefix "\\")
               (lean4-input-or
                (lean4-input-compose
                 (lean4-input-drop '("^o"))
                 (lean4-input-prefix "^"))
                (lean4-input-prefix "_"))))))
  "List of parent Quail input methods.
Translations from these methods will be inherited by the Lean
input method (with the exception of translations corresponding to
ASCII characters).

The list consists of pairs (qp . tweak), where qp is the name of
a Quail package, and tweak is an expression of the same signature as
the argument of `lean4-input-add-translations'.

The inherited translation pairs are added last, after
`lean4-input-user-translations' and `lean4-input-translations'.

If you change this setting manually (without using the
customization buffer) you need to call `lean4-input-setup' in
order for the change to take effect."
  :group 'lean4-input
  :set 'lean4-input-incorporate-changed-setting
  :initialize 'custom-initialize-default
  :type '(repeat (cons (string :tag "Quail package")
                       (sexp :tag "Tweaking function"))))

(defcustom lean4-input-user-translations nil
  "A list of translations specific to the Lean input method.

Each element is a pair (KEY-SEQUENCE-STRING
. LIST-OF-TRANSLATION-STRINGS).  All the translation strings are
possible translations of the given key sequence; if there is more than
one you can choose between them using the arrow keys.

These translation pairs are included first, before thoseinherited
from other input methods."
  :group 'lean4-input
  :set 'lean4-input-incorporate-changed-setting
  :initialize 'custom-initialize-default
  :type '(repeat (cons (string :tag "Key sequence")
                       (repeat :tag "Translations" string))))

;;;; Inspecting and modifying translation maps

(defun lean4-input-get-translations (qp)
  "Return all translations from the Quail package QP.

Result is a list of pairs (KEY-SEQUENCE . TRANSLATION) that contains
all translations from QP Except for those corresponding to ASCII."
  (with-temp-buffer
    ;; Make sure that the package is loaded.
    (activate-input-method qp)
    (unless (quail-package qp)
      (error "%s is not a Quail package" qp))
    (let ((decode-map (list 'decode-map)))
      (quail-build-decode-map (list (quail-map)) "" decode-map 0)
      (cdr decode-map))))

(defun lean4-input-show-translations (qp)
  "Display all translations used by the Quail package QP (a string).

(Except for those corresponding to ASCII)."
  (interactive (list (read-input-method-name
                      "Quail input method (default %s): " "Lean")))
  (let ((buf (concat "*" qp " input method translations*")))
    (with-output-to-temp-buffer buf
      (with-current-buffer buf
        (quail-insert-decode-map
         (cons 'decode-map (lean4-input-get-translations qp)))))))

(defun lean4-input-add-translations (trans)
  "Add the given translations TRANS to the Lean input method.

TRANS is a list of pairs (KEY-SEQUENCE . TRANSLATION).  The
translations are appended to the current translations."
  (with-temp-buffer
    (map-do (lambda (key tr)
              (when key
                (quail-defrule (concat "\\" key)
                               tr
                               "Lean" t)))
            trans)))

(defun lean4-input-inherit-package (qp &optional fun)
  "Inherit translations from the Quail package QP.

Add all translations from the Quail package QP (except for those
corresponding to ASCII) to the list of Lean Quail rules.

The optional function FUN can be used to modify the translations.
It is given a pair (KEY-SEQUENCE . TRANSLATION) and should return
a list of such pairs."
  (let ((trans (lean4-input-get-translations qp)))
    (lean4-input-add-translations
     (if fun (lean4-input-concat-map fun trans)
       trans))))

;;;; Setting up the input method

;; TODO: Research how to optimize this.  It'd be good if we did not
;; put all of these translations in a linked list in memory.
(defcustom lean4-input-translations
  '(("!!" . ["‼"])
    ("!" . ["¡"])
    ("!?" . ["⁉"])
    ("#" . ["♯"])
    ("&" . ["⅋"])
    ("'A" . ["Á"])
    ("'E" . ["É"])
    ("'I" . ["Í"])
    ("'O" . ["Ó"])
    ("'U" . ["Ú"])
    ("'Y" . ["Ý"])
    ("'a" . ["á"])
    ("'e" . ["é"])
    ("'i" . ["í"])
    ("'o" . ["ó"])
    ("'u" . ["ú"])
    ("'y" . ["ý"])
    ("(=" . ["≘"])
    ("([" . ["⟮"])
    ("(b" . ["⟅"])
    (")b" . ["⟆"])
    ("*" . ["⋆"])
    ("*=" . ["≛"])
    ("+ " . ["⊹"])
    ("-" . ["⁻¹"])
    ("---" . ["─"])
    ("--." . ["╌"])
    ("--=" . ["═"])
    ("-->" . ["⟶"])
    ("--_" . ["━"])
    ("-1" . ["⁻¹"])
    ("-2" . ["⁻²"])
    ("-3" . ["⁻³"])
    ("-:" . ["∹"])
    ("->" . ["→"])
    ("->n" . ["↛"])
    ("-]" . ["⁆"])
    ("-o" . ["⊸"])
    ("-|" . ["⊣"])
    ("-~" . ["≂"])
    ("." . ["·"])
    (".+" . ["∔"])
    (".-" . ["∸"])
    ("..." . ["⋯"])
    (".=" . ["≐"])
    (".=." . ["≑"])
    ("/" . ["⧸"])
    ("/L" . ["Ł"])
    ("/O" . ["Ø"])
    ("/o" . ["ø"])
    ("0" . ["₀"])
    ("1" . ["₁"])
    ("2" . ["₂"])
    ("3" . ["₃"])
    ("4" . ["₄"])
    ("5" . ["₅"])
    ("6" . ["₆"])
    ("7" . ["₇"])
    ("8" . ["₈"])
    ("8<" . ["✂"])
    ("9" . ["₉"])
    (":" . ["∶"])
    ("::" . ["∷"])
    ("::-" . ["∺"])
    (":=" . ["≔"])
    (":>" . ["⋗"])
    (":~" . ["∻"])
    ("<" . ["⟨"])
    ("<-" . ["←"])
    ("<--" . ["⟵"])
    ("<-->" . ["⟷"])
    ("<->" . ["↔"])
    ("<->n" . ["↮"])
    ("<-n" . ["↚"])
    ("<:" . ["⋖"])
    ("<<" . ["⟪"])
    ("<=" . ["≤"])
    ("<=>" . ["⇔"])
    ("<=>n" . ["⇎"])
    ("<=n" . ["≰"])
    ("<n" . ["≮"])
    ("<|" . ["⧏"])
    ("<~" . ["≲"])
    ("<~n" . ["⋦"])
    ("<~nn" . ["≴"])
    ("=:" . ["≕"])
    ("==" . ["≡"])
    ("===" . ["≣"])
    ("==>" . ["⟹"])
    ("==n" . ["≢"])
    ("=>" . ["⇒"])
    ("=>n" . ["⇏"])
    ("=n" . ["≠"])
    ("=o" . ["≗"])
    (">" . ["⟩"])
    (">=" . ["≥"])
    (">=n" . ["≱"])
    (">>" . ["⟫"])
    (">n" . ["≯"])
    (">~" . ["≳"])
    (">~n" . ["⋧"])
    (">~nn" . ["≵"])
    ("?!" . ["‽"])
    ("?" . ["¿"])
    ("?=" . ["≟"])
    ("??" . ["⁇"])
    ("A" . ["𝔸"])
    ("AA" . ["Å"])
    ("AE" . ["Æ"])
    ("Alpha" . ["Α"])
    ("And" . ["⋀"])
    ("Beta" . ["Β"])
    ("Box" . ["□"])
    ("Bumpeq" . ["≎"])
    ("C" . ["ℂ"])
    ("Cap" . ["⋒"])
    ("Chi" . ["Χ"])
    ("Com" . ["ℂ"])
    ("Complement" . ["∁"])
    ("Cup" . ["⋓"])
    ("D" . ["Δ"])
    ("DH" . ["Ð"])
    ("Dei" . ["Ϯ"])
    ("Delta" . ["Δ"])
    ("Diamond" . ["◇"])
    ("Digamma" . ["Ϝ"])
    ("Downarrow" . ["⇓"])
    ("Epsilon" . ["Ε"])
    ("Eta" . ["Η"])
    ("F" . ["𝔽"])
    ("Fei" . ["Ϥ"])
    ("Frowny" . ["☹"])
    ("G" . ["Γ"])
    ("GA" . ["Α"])
    ("GB" . ["Β"])
    ("GC" . ["Χ"])
    ("GD" . ["Δ"])
    ("GE" . ["Ε"])
    ("GF" . ["Φ"])
    ("GG" . ["Γ"])
    ("GI" . ["Ι"])
    ("GK" . ["Κ"])
    ("GL" . ["Λ"])
    ("GM" . ["Μ"])
    ("GN" . ["Ν"])
    ("GO" . ["Ω"])
    ("GP" . ["Ψ"])
    ("GR" . ["Ρ"])
    ("GS" . ["Σ"])
    ("GT" . ["Τ"])
    ("GTH" . ["Θ"])
    ("GU" . ["Υ"])
    ("GX" . ["Ξ"])
    ("GZ" . ["Ζ"])
    ("Ga" . ["α"])
    ("Gamma" . ["Γ"])
    ("Gangia" . ["Ϫ"])
    ("Gb" . ["β"])
    ("Gc" . ["χ"])
    ("Gd" . ["δ"])
    ("Ge" . ["ε"])
    ("Gf" . ["φ"])
    ("Gg" . ["γ"])
    ("Gi" . ["ι"])
    ("Gk" . ["κ"])
    ("Gl" . ["λ"])
    ("Gl-" . ["ƛ"])
    ("Glb" . ["⨅"])
    ("Gm" . ["μ"])
    ("Gn" . ["ν"])
    ("Go" . ["ω"])
    ("Gp" . ["ψ"])
    ("Gr" . ["ρ"])
    ("Gs" . ["σ"])
    ("Gt" . ["τ"])
    ("Gth" . ["θ"])
    ("Gu" . ["υ"])
    ("Gx" . ["ξ"])
    ("Gz" . ["ζ"])
    ("H" . ["ℍ"])
    ("Heta" . ["Ͱ"])
    ("Hori" . ["Ϩ"])
    ("I" . ["⋂"])
    ("I0" . ["⋂₀"])
    ("Im" . ["ℑ"])
    ("Inf" . ["⨅"])
    ("Int" . ["ℤ"])
    ("Inter" . ["⋂"])
    ("Iota" . ["Ι"])
    ("Join" . ["⨆"])
    ("K" . ["𝕂"])
    ("Kappa" . ["Κ"])
    ("Khei" . ["Ϧ"])
    ("Koppa" . ["Ϟ"])
    ("L" . ["Λ"])
    ("Lambda" . ["Λ"])
    ("Lamda" . ["Λ"])
    ("Leftarrow" . ["⇐"])
    ("Leftrightarrow" . ["⇔"])
    ("Letter" . ["✉"])
    ("Ll" . ["⋘"])
    ("Lleftarrow" . ["⇚"])
    ("Longleftarrow" . ["⇐"])
    ("Longleftrightarrow" . ["⇔"])
    ("Longrightarrow" . ["⇒"])
    ("Lsh" . ["↰"])
    ("Lub" . ["⨆"])
    ("MCA" . ["𝓐"])
    ("MCB" . ["𝓑"])
    ("MCC" . ["𝓒"])
    ("MCD" . ["𝓓"])
    ("MCE" . ["𝓔"])
    ("MCF" . ["𝓕"])
    ("MCG" . ["𝓖"])
    ("MCH" . ["𝓗"])
    ("MCI" . ["𝓘"])
    ("MCJ" . ["𝓙"])
    ("MCK" . ["𝓚"])
    ("MCL" . ["𝓛"])
    ("MCM" . ["𝓜"])
    ("MCN" . ["𝓝"])
    ("MCO" . ["𝓞"])
    ("MCP" . ["𝓟"])
    ("MCQ" . ["𝓠"])
    ("MCR" . ["𝓡"])
    ("MCS" . ["𝓢"])
    ("MCT" . ["𝓣"])
    ("MCU" . ["𝓤"])
    ("MCV" . ["𝓥"])
    ("MCW" . ["𝓦"])
    ("MCX" . ["𝓧"])
    ("MCY" . ["𝓨"])
    ("MCZ" . ["𝓩"])
    ("MCa" . ["𝓪"])
    ("MCb" . ["𝓫"])
    ("MCc" . ["𝓬"])
    ("MCd" . ["𝓭"])
    ("MCe" . ["𝓮"])
    ("MCf" . ["𝓯"])
    ("MCg" . ["𝓰"])
    ("MCh" . ["𝓱"])
    ("MCi" . ["𝓲"])
    ("MCj" . ["𝓳"])
    ("MCk" . ["𝓴"])
    ("MCl" . ["𝓵"])
    ("MCm" . ["𝓶"])
    ("MCn" . ["𝓷"])
    ("MCo" . ["𝓸"])
    ("MCp" . ["𝓹"])
    ("MCq" . ["𝓺"])
    ("MCr" . ["𝓻"])
    ("MCs" . ["𝓼"])
    ("MCt" . ["𝓽"])
    ("MCu" . ["𝓾"])
    ("MCv" . ["𝓿"])
    ("MCw" . ["𝔀"])
    ("MCx" . ["𝔁"])
    ("MCy" . ["𝔂"])
    ("MCz" . ["𝔃"])
    ("MIA" . ["𝑨"])
    ("MIB" . ["𝑩"])
    ("MIC" . ["𝑪"])
    ("MID" . ["𝑫"])
    ("MIE" . ["𝑬"])
    ("MIF" . ["𝑭"])
    ("MIG" . ["𝑮"])
    ("MIH" . ["𝑯"])
    ("MII" . ["𝑰"])
    ("MIJ" . ["𝑱"])
    ("MIK" . ["𝑲"])
    ("MIL" . ["𝑳"])
    ("MIM" . ["𝑴"])
    ("MIN" . ["𝑵"])
    ("MIO" . ["𝑶"])
    ("MIP" . ["𝑷"])
    ("MIQ" . ["𝑸"])
    ("MIR" . ["𝑹"])
    ("MIS" . ["𝑺"])
    ("MIT" . ["𝑻"])
    ("MIU" . ["𝑼"])
    ("MIV" . ["𝑽"])
    ("MIW" . ["𝑾"])
    ("MIX" . ["𝑿"])
    ("MIY" . ["𝒀"])
    ("MIZ" . ["𝒁"])
    ("MIa" . ["𝒂"])
    ("MIb" . ["𝒃"])
    ("MIc" . ["𝒄"])
    ("MId" . ["𝒅"])
    ("MIe" . ["𝒆"])
    ("MIf" . ["𝒇"])
    ("MIg" . ["𝒈"])
    ("MIh" . ["𝒉"])
    ("MIi" . ["𝒊"])
    ("MIj" . ["𝒋"])
    ("MIk" . ["𝒌"])
    ("MIl" . ["𝒍"])
    ("MIm" . ["𝒎"])
    ("MIn" . ["𝒏"])
    ("MIo" . ["𝒐"])
    ("MIp" . ["𝒑"])
    ("MIq" . ["𝒒"])
    ("MIr" . ["𝒓"])
    ("MIs" . ["𝒔"])
    ("MIt" . ["𝒕"])
    ("MIu" . ["𝒖"])
    ("MIv" . ["𝒗"])
    ("MIw" . ["𝒘"])
    ("MIx" . ["𝒙"])
    ("MIy" . ["𝒚"])
    ("MIz" . ["𝒛"])
    ("McA" . ["𝒜"])
    ("McB" . ["ℬ"])
    ("McC" . ["𝒞"])
    ("McD" . ["𝒟"])
    ("McE" . ["ℰ"])
    ("McF" . ["ℱ"])
    ("McG" . ["𝒢"])
    ("McH" . ["ℋ"])
    ("McI" . ["ℐ"])
    ("McJ" . ["𝒥"])
    ("McK" . ["𝒦"])
    ("McL" . ["ℒ"])
    ("McM" . ["ℳ"])
    ("McN" . ["𝒩"])
    ("McO" . ["𝒪"])
    ("McP" . ["𝒫"])
    ("McQ" . ["𝒬"])
    ("McR" . ["ℛ"])
    ("McS" . ["𝒮"])
    ("McT" . ["𝒯"])
    ("McU" . ["𝒰"])
    ("McV" . ["𝒱"])
    ("McW" . ["𝒲"])
    ("McX" . ["𝒳"])
    ("McY" . ["𝒴"])
    ("McZ" . ["𝒵"])
    ("Mca" . ["𝒶"])
    ("Mcb" . ["𝒷"])
    ("Mcc" . ["𝒸"])
    ("Mcd" . ["𝒹"])
    ("Mce" . ["ℯ"])
    ("Mcf" . ["𝒻"])
    ("Mcg" . ["ℊ"])
    ("Mch" . ["𝒽"])
    ("Mci" . ["𝒾"])
    ("Mcj" . ["𝒿"])
    ("Mck" . ["𝓀"])
    ("Mcl" . ["𝓁"])
    ("Mcm" . ["𝓂"])
    ("Mcn" . ["𝓃"])
    ("Mco" . ["ℴ"])
    ("Mcp" . ["𝓅"])
    ("Mcq" . ["𝓆"])
    ("Mcr" . ["𝓇"])
    ("Mcs" . ["𝓈"])
    ("Mct" . ["𝓉"])
    ("Mcu" . ["𝓊"])
    ("Mcv" . ["𝓋"])
    ("Mcw" . ["𝓌"])
    ("Mcx" . ["𝓍"])
    ("Mcy" . ["𝓎"])
    ("Mcz" . ["𝓏"])
    ("Meet" . ["⨅"])
    ("MfA" . ["𝔄"])
    ("MfB" . ["𝔅"])
    ("MfC" . ["ℭ"])
    ("MfD" . ["𝔇"])
    ("MfE" . ["𝔈"])
    ("MfF" . ["𝔉"])
    ("MfG" . ["𝔊"])
    ("MfH" . ["ℌ"])
    ("MfI" . ["ℑ"])
    ("MfJ" . ["𝔍"])
    ("MfK" . ["𝔎"])
    ("MfL" . ["𝔏"])
    ("MfM" . ["𝔐"])
    ("MfN" . ["𝔑"])
    ("MfO" . ["𝔒"])
    ("MfP" . ["𝔓"])
    ("MfQ" . ["𝔔"])
    ("MfR" . ["ℜ"])
    ("MfS" . ["𝔖"])
    ("MfT" . ["𝔗"])
    ("MfU" . ["𝔘"])
    ("MfV" . ["𝔙"])
    ("MfW" . ["𝔚"])
    ("MfX" . ["𝔛"])
    ("MfY" . ["𝔜"])
    ("MfZ" . ["ℨ"])
    ("Mfa" . ["𝔞"])
    ("Mfb" . ["𝔟"])
    ("Mfc" . ["𝔠"])
    ("Mfd" . ["𝔡"])
    ("Mfe" . ["𝔢"])
    ("Mff" . ["𝔣"])
    ("Mfg" . ["𝔤"])
    ("Mfh" . ["𝔥"])
    ("Mfi" . ["𝔦"])
    ("Mfj" . ["𝔧"])
    ("Mfk" . ["𝔨"])
    ("Mfl" . ["𝔩"])
    ("Mfm" . ["𝔪"])
    ("Mfn" . ["𝔫"])
    ("Mfo" . ["𝔬"])
    ("Mfp" . ["𝔭"])
    ("Mfq" . ["𝔮"])
    ("Mfr" . ["𝔯"])
    ("Mfs" . ["𝔰"])
    ("Mft" . ["𝔱"])
    ("Mfu" . ["𝔲"])
    ("Mfv" . ["𝔳"])
    ("Mfw" . ["𝔴"])
    ("Mfx" . ["𝔵"])
    ("Mfy" . ["𝔶"])
    ("Mfz" . ["𝔷"])
    ("MiA" . ["𝐴"])
    ("MiB" . ["𝐵"])
    ("MiC" . ["𝐶"])
    ("MiD" . ["𝐷"])
    ("MiE" . ["𝐸"])
    ("MiF" . ["𝐹"])
    ("MiG" . ["𝐺"])
    ("MiH" . ["𝐻"])
    ("MiI" . ["𝐼"])
    ("MiJ" . ["𝐽"])
    ("MiK" . ["𝐾"])
    ("MiL" . ["𝐿"])
    ("MiM" . ["𝑀"])
    ("MiN" . ["𝑁"])
    ("MiO" . ["𝑂"])
    ("MiP" . ["𝑃"])
    ("MiQ" . ["𝑄"])
    ("MiR" . ["𝑅"])
    ("MiS" . ["𝑆"])
    ("MiT" . ["𝑇"])
    ("MiU" . ["𝑈"])
    ("MiV" . ["𝑉"])
    ("MiW" . ["𝑊"])
    ("MiX" . ["𝑋"])
    ("MiY" . ["𝑌"])
    ("MiZ" . ["𝑍"])
    ("Mia" . ["𝑎"])
    ("Mib" . ["𝑏"])
    ("Mic" . ["𝑐"])
    ("Mid" . ["𝑑"])
    ("Mie" . ["𝑒"])
    ("Mif" . ["𝑓"])
    ("Mig" . ["𝑔"])
    ("Mii" . ["𝑖"])
    ("Mij" . ["𝑗"])
    ("Mik" . ["𝑘"])
    ("Mil" . ["𝑙"])
    ("Mim" . ["𝑚"])
    ("Min" . ["𝑛"])
    ("Mio" . ["𝑜"])
    ("Mip" . ["𝑝"])
    ("Miq" . ["𝑞"])
    ("Mir" . ["𝑟"])
    ("Mis" . ["𝑠"])
    ("Mit" . ["𝑡"])
    ("Miu" . ["𝑢"])
    ("Miv" . ["𝑣"])
    ("Miw" . ["𝑤"])
    ("Mix" . ["𝑥"])
    ("Miy" . ["𝑦"])
    ("Miz" . ["𝑧"])
    ("N" . ["ℕ"])
    ("Nat" . ["ℕ"])
    ("Nu" . ["Ν"])
    ("O" . ["Ø"])
    ("O*" . ["⍟"])
    ("O+" . ["⨁"])
    ("O." . ["⨀"])
    ("OE" . ["Œ"])
    ("Omega" . ["Ω"])
    ("Omicron" . ["Ο"])
    ("Or" . ["⋁"])
    ("Ox" . ["⨂"])
    ("P" . ["Π"])
    ("P0" . ["Π₀"])
    ("P_0" . ["Π₀"])
    ("Phi" . ["Φ"])
    ("Pi" . ["Π"])
    ("Pi0" . ["Π₀"])
    ("Pi_0" . ["Π₀"])
    ("Psi" . ["Ψ"])
    ("Q" . ["ℚ"])
    ("R" . ["ℝ"])
    ("R>=0" . ["ℝ≥0"])
    ("Rat" . ["ℚ"])
    ("Re" . ["ℜ"])
    ("Real" . ["ℝ"])
    ("Rge0" . ["ℝ≥0"])
    ("Rho" . ["Ρ"])
    ("Rightarrow" . ["⇒"])
    ("Rrightarrow" . ["⇛"])
    ("Rsh" . ["↱"])
    ("S" . ["Σ"])
    ("Sampi" . ["Ϡ"])
    ("San" . ["Ϻ"])
    ("Shei" . ["Ϣ"])
    ("Shima" . ["Ϭ"])
    ("Sho" . ["Ϸ"])
    ("Sigma" . ["Σ"])
    ("Smiley" . ["☺"])
    ("Sqcap" . ["⨅"])
    ("Sqcup" . ["⨆"])
    ("Stigma" . ["Ϛ"])
    ("Subset" . ["⋐"])
    ("Sup" . ["⨆"])
    ("Supset" . ["⋑"])
    ("TH" . ["Þ"])
    ("Tau" . ["Τ"])
    ("Tb" . ["◀"])
    ("Theta" . ["Θ"])
    ("Tr" . ["◀"])
    ("Tw" . ["◁"])
    ("U" . ["⋃"])
    ("U+" . ["⨄"])
    ("U." . ["⨃"])
    ("U0" . ["⋃₀"])
    ("Un" . ["⋃"])
    ("Union" . ["⋃"])
    ("Uparrow" . ["⇑"])
    ("Updownarrow" . ["⇕"])
    ("Upsilon" . ["Υ"])
    ("Vdash" . ["⊩"])
    ("Vert" . ["‖"])
    ("Vvdash" . ["⊪"])
    ("X" . ["⨯"])
    ("Xi" . ["Ξ"])
    ("Yot" . ["Ϳ"])
    ("Z" . ["ℤ"])
    ("Zeta" . ["Ζ"])
    ("Zsqrt" . ["ℤ√"])
    ("[-" . ["⁅"])
    ("[[" . ["⟦"])
    ("\"A" . ["Ä"])
    ("\"E" . ["Ë"])
    ("\"I" . ["Ï"])
    ("\"O" . ["Ö"])
    ("\"U" . ["Ü"])
    ("\"a" . ["ä"])
    ("\"e" . ["ë"])
    ("\"i" . ["ï"])
    ("\"o" . ["ö"])
    ("\"u" . ["ü"])
    ("\"y" . ["ÿ"])
    ("\\" . ["\\"])
    ("])" . ["⟯"])
    ("]]" . ["⟧"])
    ("^(" . ["⁽"])
    ("^)" . ["⁾"])
    ("^+" . ["⁺"])
    ("^-" . ["⁻"])
    ("^-1" . ["⁻¹"])
    ("^0" . ["⁰"])
    ("^1" . ["¹"])
    ("^2" . ["²"])
    ("^3" . ["³"])
    ("^4" . ["⁴"])
    ("^5" . ["⁵"])
    ("^6" . ["⁶"])
    ("^7" . ["⁷"])
    ("^8" . ["⁸"])
    ("^9" . ["⁹"])
    ("^=" . ["⁼"])
    ("^A" . ["ᴬ"])
    ("^Ae" . ["ᴭ"])
    ("^B" . ["ᴮ"])
    ("^Bbarred" . ["ᴯ"])
    ("^D" . ["ᴰ"])
    ("^E" . ["ᴱ"])
    ("^Ereversed" . ["ᴲ"])
    ("^G" . ["ᴳ"])
    ("^H" . ["ᴴ"])
    ("^Hstroke" . ["ꟸ"])
    ("^I" . ["ᴵ"])
    ("^Ismall" . ["ᶦ"])
    ("^Istroke" . ["ᶧ"])
    ("^J" . ["ᴶ"])
    ("^K" . ["ᴷ"])
    ("^L" . ["ᴸ"])
    ("^Lsmall" . ["ᶫ"])
    ("^M" . ["ᴹ"])
    ("^N" . ["ᴺ"])
    ("^Nreversed" . ["ᴻ"])
    ("^Nsmall" . ["ᶰ"])
    ("^O" . ["ᴼ"])
    ("^Ou" . ["ᴽ"])
    ("^P" . ["ᴾ"])
    ("^R" . ["ᴿ"])
    ("^Rinverted" . ["ʶ"])
    ("^SM" . ["℠"])
    ("^T" . ["ᵀ"])
    ("^TEL" . ["℡"])
    ("^TM" . ["™"])
    ("^U" . ["ᵁ"])
    ("^Usmall" . ["ᶸ"])
    ("^V" . ["ⱽ"])
    ("^W" . ["ᵂ"])
    ("^a" . ["ᵃ"])
    ("^a_" . ["ª"])
    ("^ain" . ["ᵜ"])
    ("^alpha" . ["ᵅ"])
    ("^b" . ["ᵇ"])
    ("^beta" . ["ᵝ"])
    ("^bot" . ["ᗮ"])
    ("^c" . ["ᶜ"])
    ("^ccurl" . ["ᶝ"])
    ("^chi" . ["ᵡ"])
    ("^d" . ["ᵈ"])
    ("^e" . ["ᵉ"])
    ("^eng" . ["ᵑ"])
    ("^eopen" . ["ᵋ"])
    ("^ereversedopen" . ["ᶟ"])
    ("^esh" . ["ᶴ"])
    ("^eth" . ["ᶞ"])
    ("^ezh" . ["ᶾ"])
    ("^f" . ["ᶠ"])
    ("^g" . ["ᵍ"])
    ("^gamma" . ["ˠ"])
    ("^gscript" . ["ᶢ"])
    ("^h" . ["ʰ"])
    ("^heng" . ["ꭜ"])
    ("^hhook" . ["ʱ"])
    ("^hwithhook" . ["ʱ"])
    ("^i" . ["ⁱ"])
    ("^iota" . ["ᶥ"])
    ("^istroke" . ["ᶤ"])
    ("^j" . ["ʲ"])
    ("^jtail" . ["ᶨ"])
    ("^k" . ["ᵏ"])
    ("^l" . ["ˡ"])
    ("^lhook" . ["ᶪ"])
    ("^lretroflexhook" . ["ᶩ"])
    ("^ls" . ["ꭝ"])
    ("^ltilde" . ["ꭞ"])
    ("^m" . ["ᵐ"])
    ("^mhook" . ["ᶬ"])
    ("^n" . ["ⁿ"])
    ("^nlefthook" . ["ᶮ"])
    ("^nretroflexhook" . ["ᶯ"])
    ("^o" . ["ᵒ"])
    ("^o_" . ["º"])
    ("^obarred" . ["ᶱ"])
    ("^obottom" . ["ᵕ"])
    ("^oe" . ["ꟹ"])
    ("^oopen" . ["ᵓ"])
    ("^otop" . ["ᵔ"])
    ("^p" . ["ᵖ"])
    ("^perp" . ["ᗮ"])
    ("^phi" . ["ᶲ"])
    ("^r" . ["ʳ"])
    ("^s" . ["ˢ"])
    ("^schwa" . ["ᵊ"])
    ("^shook" . ["ᶳ"])
    ("^stop" . ["ˤ"])
    ("^t" . ["ᵗ"])
    ("^theta" . ["ᶿ"])
    ("^turneda" . ["ᵄ"])
    ("^turnedae" . ["ᵆ"])
    ("^turnedalpha" . ["ᶛ"])
    ("^turnede" . ["ᵌ"])
    ("^turnedh" . ["ᶣ"])
    ("^turnedi" . ["ᵎ"])
    ("^turnedm" . ["ᵚ"])
    ("^turnedmleg" . ["ᶭ"])
    ("^turnedr" . ["ʴ"])
    ("^turnedrhook" . ["ʵ"])
    ("^turnedrwithhook" . ["ʵ"])
    ("^turnedv" . ["ᶺ"])
    ("^twithpalatalhook" . ["ᶵ"])
    ("^u" . ["ᵘ"])
    ("^ubar" . ["ᶶ"])
    ("^uhook" . ["ꭟ"])
    ("^upsilon" . ["ᶷ"])
    ("^usideways" . ["ᵙ"])
    ("^v" . ["ᵛ"])
    ("^vargamma" . ["ᵞ"])
    ("^varphi" . ["ᵠ"])
    ("^vhook" . ["ᶹ"])
    ("^w" . ["ʷ"])
    ("^x" . ["ˣ"])
    ("^y" . ["ʸ"])
    ("^z" . ["ᶻ"])
    ("^zcurl" . ["ᶽ"])
    ("^zretroflexhook" . ["ᶼ"])
    ("^{A}" . ["Â"])
    ("^{E}" . ["Ê"])
    ("^{I}" . ["Î"])
    ("^{O}" . ["Ô"])
    ("^{U}" . ["Û"])
    ("^{a}" . ["â"])
    ("^{e}" . ["ê"])
    ("^{i}" . ["î"])
    ("^{o}" . ["ô"])
    ("^{u}" . ["û"])
    ("_(" . ["₍"])
    ("_)" . ["₎"])
    ("_+" . ["₊"])
    ("_-" . ["₋"])
    ("_--" . ["̲"])
    ("_0" . ["₀"])
    ("_1" . ["₁"])
    ("_2" . ["₂"])
    ("_3" . ["₃"])
    ("_4" . ["₄"])
    ("_5" . ["₅"])
    ("_6" . ["₆"])
    ("_7" . ["₇"])
    ("_8" . ["₈"])
    ("_9" . ["₉"])
    ("_=" . ["₌"])
    ("_a" . ["ₐ"])
    ("_e" . ["ₑ"])
    ("_h" . ["ₕ"])
    ("_i" . ["ᵢ"])
    ("_j" . ["ⱼ"])
    ("_k" . ["ₖ"])
    ("_l" . ["ₗ"])
    ("_m" . ["ₘ"])
    ("_n" . ["ₙ"])
    ("_o" . ["ₒ"])
    ("_p" . ["ₚ"])
    ("_r" . ["ᵣ"])
    ("_s" . ["ₛ"])
    ("_t" . ["ₜ"])
    ("_u" . ["ᵤ"])
    ("_v" . ["ᵥ"])
    ("_x" . ["ₓ"])
    ("`A" . ["À"])
    ("`E" . ["È"])
    ("`I" . ["Ì"])
    ("`O" . ["Ò"])
    ("`U" . ["Ù"])
    ("`a" . ["à"])
    ("`e" . ["è"])
    ("`i" . ["ì"])
    ("`o" . ["ò"])
    ("`u" . ["ù"])
    ("a" . ["α"])
    ("aa" . ["å"])
    ("ae" . ["æ"])
    ("aeeqfun" . ["→ₘ"])
    ("afghani" . ["؋"])
    ("aleph" . ["ℵ"])
    ("alghom" . ["→ₐ"])
    ("all" . ["∀"])
    ("all^f" . ["∀ᶠ"])
    ("all^m" . ["∀ᵐ"])
    ("allf" . ["∀ᶠ"])
    ("allm" . ["∀ᵐ"])
    ("alpha" . ["α"])
    ("amalg" . ["∐"])
    ("an" . ["∧"])
    ("and" . ["∧"])
    ("and=" . ["≙"])
    ("angle" . ["∠"])
    ("angstrom" . ["Å"])
    ("aop" . ["ᵃᵒᵖ"])
    ("apl" . ["⌶"])
    ("approx" . ["≈"])
    ("approxeq" . ["≊"])
    ("ast" . ["∗"])
    ("asterisk" . ["⁎"])
    ("asymp" . ["≍"])
    ("austral" . ["₳"])
    ("b" . ["β"])
    ("b+" . ["⊞"])
    ("b-" . ["⊟"])
    ("b." . ["⊡"])
    ("b0" . ["𝟘"])
    ("b1" . ["𝟙"])
    ("b2" . ["𝟚"])
    ("b3" . ["𝟛"])
    ("b4" . ["𝟜"])
    ("b5" . ["𝟝"])
    ("b6" . ["𝟞"])
    ("b7" . ["𝟟"])
    ("b8" . ["𝟠"])
    ("b9" . ["𝟡"])
    ("bInter" . ["⋂"])
    ("bUnion" . ["⋃"])
    ("backcong" . ["≌"])
    ("backepsilon" . ["∍"])
    ("backprime" . ["‵"])
    ("backsim" . ["∽"])
    ("backsimeq" . ["⋍"])
    ("barwedge" . ["⊼"])
    ("bb" . ["𝔹"])
    ("bbA" . ["𝔸"])
    ("bbB" . ["𝔹"])
    ("bbC" . ["ℂ"])
    ("bbD" . ["𝔻"])
    ("bbE" . ["𝔼"])
    ("bbF" . ["𝔽"])
    ("bbG" . ["𝔾"])
    ("bbH" . ["ℍ"])
    ("bbI" . ["𝕀"])
    ("bbJ" . ["𝕁"])
    ("bbK" . ["𝕂"])
    ("bbL" . ["𝕃"])
    ("bbM" . ["𝕄"])
    ("bbN" . ["ℕ"])
    ("bbO" . ["𝕆"])
    ("bbP" . ["ℙ"])
    ("bbQ" . ["ℚ"])
    ("bbR" . ["ℝ"])
    ("bbS" . ["𝕊"])
    ("bbT" . ["𝕋"])
    ("bbU" . ["𝕌"])
    ("bbV" . ["𝕍"])
    ("bbW" . ["𝕎"])
    ("bbX" . ["𝕏"])
    ("bbY" . ["𝕐"])
    ("bbZ" . ["ℤ"])
    ("bba" . ["𝕒"])
    ("bbb" . ["𝕓"])
    ("bbc" . ["𝕔"])
    ("bbd" . ["𝕕"])
    ("bbe" . ["𝕖"])
    ("bbf" . ["𝕗"])
    ("bbg" . ["𝕘"])
    ("bbh" . ["𝕙"])
    ("bbi" . ["𝕚"])
    ("bbj" . ["𝕛"])
    ("bbk" . ["𝕜"])
    ("bbl" . ["𝕝"])
    ("bbm" . ["𝕞"])
    ("bbn" . ["𝕟"])
    ("bbo" . ["𝕠"])
    ("bbp" . ["𝕡"])
    ("bbq" . ["𝕢"])
    ("bbr" . ["𝕣"])
    ("bbs" . ["𝕤"])
    ("bbt" . ["𝕥"])
    ("bbu" . ["𝕦"])
    ("bbv" . ["𝕧"])
    ("bbw" . ["𝕨"])
    ("bbx" . ["𝕩"])
    ("bby" . ["𝕪"])
    ("bbz" . ["𝕫"])
    ("bc" . ["ℂ"])
    ("be" . ["β"])
    ("because" . ["∵"])
    ("beta" . ["β"])
    ("beth" . ["ℶ"])
    ("between" . ["≬"])
    ("bfA" . ["𝐀"])
    ("bfB" . ["𝐁"])
    ("bfC" . ["𝐂"])
    ("bfD" . ["𝐃"])
    ("bfE" . ["𝐄"])
    ("bfF" . ["𝐅"])
    ("bfG" . ["𝐆"])
    ("bfH" . ["𝐇"])
    ("bfI" . ["𝐈"])
    ("bfJ" . ["𝐉"])
    ("bfK" . ["𝐊"])
    ("bfL" . ["𝐋"])
    ("bfM" . ["𝐌"])
    ("bfN" . ["𝐍"])
    ("bfO" . ["𝐎"])
    ("bfP" . ["𝐏"])
    ("bfQ" . ["𝐐"])
    ("bfR" . ["𝐑"])
    ("bfS" . ["𝐒"])
    ("bfT" . ["𝐓"])
    ("bfU" . ["𝐔"])
    ("bfV" . ["𝐕"])
    ("bfW" . ["𝐖"])
    ("bfX" . ["𝐗"])
    ("bfY" . ["𝐘"])
    ("bfZ" . ["𝐙"])
    ("bfa" . ["𝐚"])
    ("bfb" . ["𝐛"])
    ("bfc" . ["𝐜"])
    ("bfd" . ["𝐝"])
    ("bfe" . ["𝐞"])
    ("bff" . ["𝐟"])
    ("bfg" . ["𝐠"])
    ("bfh" . ["𝐡"])
    ("bfi" . ["𝐢"])
    ("bfj" . ["𝐣"])
    ("bfk" . ["𝐤"])
    ("bfl" . ["𝐥"])
    ("bfm" . ["𝐦"])
    ("bfn" . ["𝐧"])
    ("bfo" . ["𝐨"])
    ("bfp" . ["𝐩"])
    ("bfq" . ["𝐪"])
    ("bfr" . ["𝐫"])
    ("bfs" . ["𝐬"])
    ("bft" . ["𝐭"])
    ("bfu" . ["𝐮"])
    ("bfv" . ["𝐯"])
    ("bfw" . ["𝐰"])
    ("bfx" . ["𝐱"])
    ("bfy" . ["𝐲"])
    ("bfz" . ["𝐳"])
    ("bigcap" . ["⋂"])
    ("bigcirc" . ["◯"])
    ("bigcoprod" . ["∐"])
    ("bigcup" . ["⋃"])
    ("bigglb" . ["⨅"])
    ("biginf" . ["⨅"])
    ("bigjoin" . ["⨆"])
    ("biglub" . ["⨆"])
    ("bigmeet" . ["⨅"])
    ("bigsolidus" . ["⧸"])
    ("bigsqcap" . ["⨅"])
    ("bigsqcup" . ["⨆"])
    ("bigstar" . ["★"])
    ("bigsup" . ["⨆"])
    ("bigtriangledown" . ["▽"])
    ("bigtriangleup" . ["△"])
    ("bigvee" . ["⋁"])
    ("bigwedge" . ["⋀"])
    ("biohazard" . ["☣"])
    ("blacklozenge" . ["✦"])
    ("blacksmiley" . ["☻"])
    ("blacksquare" . ["▪"])
    ("blacktriangle" . ["▴"])
    ("blacktriangledown" . ["▾"])
    ("blacktriangleleft" . ["◂"])
    ("blacktriangleright" . ["▸"])
    ("bn" . ["ℕ"])
    ("bot" . ["⊥"])
    ("boundedcontinuousfunction" . ["→ᵇ"])
    ("bowtie" . ["⋈"])
    ("boxmid" . ["◫"])
    ("boxminus" . ["⊟"])
    ("boxplus" . ["⊞"])
    ("boxtimes" . ["⊠"])
    ("bp" . ["ℙ"])
    ("bq" . ["ℚ"])
    ("br" . ["ℝ"])
    ("bracketl" . ["⁅"])
    ("bracketr" . ["⁆"])
    ("brokenbar" . ["¦"])
    ("bsum" . ["⅀"])
    ("bu" . ["•"])
    ("bub" . ["•"])
    ("bumpeq" . ["≏"])
    ("but" . ["‣"])
    ("buw" . ["◦"])
    ("bx" . ["⊠"])
    ("bz" . ["ℤ"])
    ("c" . ["χ"])
    ("cC" . ["Ç"])
    ("c[" . ["⦃"])
    ("c]" . ["⦄"])
    ("cap" . ["∩"])
    ("caution" . ["☡"])
    ("cc" . ["ç"])
    ("cdot" . ["⬝"])
    ("cdots" . ["⋯"])
    ("ce" . ["ȩ"])
    ("cedi" . ["₵"])
    ("celsius" . ["℃"])
    ("cent" . ["¢"])
    ("centerdot" . ["·"])
    ("ch" . ["χ"])
    ("checkmark" . ["✓"])
    ("chi" . ["χ"])
    ("ci" . ["●"])
    ("ci." . ["◎"])
    ("ci.." . ["◌"])
    ("ciO" . ["◯"])
    ("cib" . ["●"])
    ("circ" . ["∘"])
    ("circeq" . ["≗"])
    ("circlearrowleft" . ["↺"])
    ("circlearrowright" . ["↻"])
    ("circledR" . ["®"])
    ("circledS" . ["Ⓢ"])
    ("circledast" . ["⊛"])
    ("circledcirc" . ["⊚"])
    ("circleddash" . ["⊝"])
    ("ciw" . ["○"])
    ("cl" . ["⌞"])
    ("clL" . ["⌊"])
    ("clR" . ["⌋"])
    ("cll" . ["⌞"])
    ("clr" . ["⌟"])
    ("clubsuit" . ["♣"])
    ("colon" . ["₡"])
    ("coloneq" . ["≔"])
    ("com" . ["ℂ"])
    ("comp" . ["∘"])
    ("compl" . ["ᶜ"])
    ("complement" . ["ᶜ"])
    ("complementprefix" . ["∁"])
    ("con" . ["⬝"])
    ("cong" . ["≅"])
    ("construction" . ["🚧"])
    ("coprod" . ["⨿"])
    ("copyright" . ["©"])
    ("covby" . ["⋖"])
    ("covers" . ["⋖"])
    ("crossproduct" . ["⨯"])
    ("cruzeiro" . ["₢"])
    ("cu" . ["⌜"])
    ("cuL" . ["⌈"])
    ("cuR" . ["⌉"])
    ("cul" . ["⌜"])
    ("cup" . ["∪"])
    ("cur" . ["⌝"])
    ("curlyeqprec" . ["⋞"])
    ("curlyeqsucc" . ["⋟"])
    ("curlypreceq" . ["≼"])
    ("curlyvee" . ["⋎"])
    ("curlywedge" . ["⋏"])
    ("currency" . ["¤"])
    ("curvearrowleft" . ["↶"])
    ("curvearrowright" . ["↷"])
    ("d" . ["↓"])
    ("d-" . ["↓"])
    ("d-2" . ["⇊"])
    ("d-u-" . ["⇵"])
    ("d-|" . ["↧"])
    ("d=" . ["⇓"])
    ("d==" . ["⟱"])
    ("dag" . ["†"])
    ("dagger" . ["†"])
    ("daleth" . ["ℸ"])
    ("dashv" . ["⊣"])
    ("dd-" . ["↡"])
    ("ddag" . ["‡"])
    ("ddagger" . ["‡"])
    ("ddots" . ["⋱"])
    ("de" . ["δ"])
    ("def=" . ["≝"])
    ("defs" . ["≙"])
    ("degree" . ["°"])
    ("dei" . ["ϯ"])
    ("delta" . ["δ"])
    ("dfinsupp" . ["→ₚ"])
    ("dh" . ["ð"])
    ("di" . ["◆"])
    ("di." . ["◈"])
    ("diameter" . ["⌀"])
    ("diamond" . ["⋄"])
    ("diamondsuit" . ["♢"])
    ("dib" . ["◆"])
    ("die" . ["⚀"])
    ("digamma" . ["ϝ"])
    ("div" . ["÷"])
    ("divideontimes" . ["⋇"])
    ("division" . ["÷"])
    ("diw" . ["◇"])
    ("dl" . ["↙"])
    ("dl-" . ["↙"])
    ("dl=" . ["⇙"])
    ("dong" . ["₫"])
    ("dot" . ["⬝"])
    ("doteq" . ["≐"])
    ("doteqdot" . ["≑"])
    ("dotplus" . ["∔"])
    ("dotsquare" . ["⊡"])
    ("downarrow" . ["↓"])
    ("downdownarrows" . ["⇊"])
    ("downleftharpoon" . ["⇃"])
    ("downrightharpoon" . ["⇂"])
    ("dr" . ["↘"])
    ("dr-" . ["↘"])
    ("dr=" . ["⇘"])
    ("drachma" . ["₯"])
    ("dz" . ["↯"])
    ("e" . ["ε"])
    ("ell" . ["ℓ"])
    ("em" . ["—"])
    ("empty" . ["∅"])
    ("emptyset" . ["∅"])
    ("en" . ["–"])
    ("ennreal" . ["ℝ≥0∞"])
    ("entails" . ["⊢"])
    ("ep" . ["ε"])
    ("eps" . ["ε"])
    ("epsilon" . ["ε"])
    ("eqcirc" . ["≖"])
    ("eqcolon" . ["≕"])
    ("eqn" . ["≠"])
    ("eqslantgtr" . ["⋝"])
    ("eqslantless" . ["⋜"])
    ("equiv" . ["≃"])
    ("et" . ["η"])
    ("eta" . ["η"])
    ("euro" . ["€"])
    ("ex" . ["∃"])
    ("exf" . ["∃ᶠ"])
    ("exists" . ["∃"])
    ("exn" . ["∄"])
    ("f<" . ["‹"])
    ("f<<" . ["«"])
    ("f>" . ["›"])
    ("f>>" . ["»"])
    ("facsimile" . ["℻"])
    ("fallingdotseq" . ["≒"])
    ("fei" . ["ϥ"])
    ("female" . ["♀"])
    ("finsupp" . ["→₀"])
    ("flat" . ["♭"])
    ("flq" . ["‹"])
    ("flqq" . ["«"])
    ("forall" . ["∀"])
    ("frac" . ["¼"])
    ("frac1" . ["⅟"])
    ("frac12" . ["½"])
    ("frac13" . ["⅓"])
    ("frac14" . ["¼"])
    ("frac15" . ["⅕"])
    ("frac16" . ["⅙"])
    ("frac18" . ["⅛"])
    ("frac23" . ["⅔"])
    ("frac25" . ["⅖"])
    ("frac34" . ["¾"])
    ("frac35" . ["⅗"])
    ("frac38" . ["⅜"])
    ("frac45" . ["⅘"])
    ("frac56" . ["⅚"])
    ("frac58" . ["⅝"])
    ("frac78" . ["⅞"])
    ("frown" . ["⌢"])
    ("frq" . ["›"])
    ("frqq" . ["»"])
    ("fun" . ["λ"])
    ("functor" . ["⥤"])
    ("fuzzy" . ["‖"])
    ("g" . ["γ"])
    ("ga" . ["γ"])
    ("gamma" . ["γ"])
    ("gangia" . ["ϫ"])
    ("ge" . ["≥"])
    ("gen" . ["≱"])
    ("geq" . ["≥"])
    ("geqn" . ["≱"])
    ("geqq" . ["≧"])
    ("geqslant" . ["≥"])
    ("gets" . ["←"])
    ("gg" . ["≫"])
    ("ggg" . ["⋙"])
    ("gimel" . ["ℷ"])
    ("glb" . ["⊓"])
    ("glq" . ["‚"])
    ("glqq" . ["„"])
    ("gnapprox" . ["⋧"])
    ("gneq" . ["≩"])
    ("gneqq" . ["≩"])
    ("gnsim" . ["⋧"])
    ("goal" . ["⊢"])
    ("grq" . ["‘"])
    ("grqq" . ["“"])
    ("gtrapprox" . ["≳"])
    ("gtrdot" . ["⋗"])
    ("gtreqless" . ["⋛"])
    ("gtreqqless" . ["⋛"])
    ("gtrless" . ["≷"])
    ("gtrsim" . ["≳"])
    ("guarani" . ["₲"])
    ("gvertneqq" . ["≩"])
    ("hbar" . ["ℏ"])
    ("hcomp" . ["◫"])
    ("heartsuit" . ["♥"])
    ("heta" . ["ͱ"])
    ("heyting" . ["⇨"])
    ("himp" . ["⇨"])
    ("hom" . ["⟶"])
    ("homotopy" . ["∼"])
    ("hookleftarrow" . ["↩"])
    ("hookrightarrow" . ["↪"])
    ("hori" . ["ϩ"])
    ("hryvnia" . ["₴"])
    ("i" . ["∩"])
    ("iff" . ["↔"])
    ("imath" . ["ı"])
    ("imp" . ["→"])
    ("in" . ["∈"])
    ("increment" . ["∆"])
    ("inf" . ["⊓"])
    ("infi" . ["⨅"])
    ("infty" . ["∞"])
    ("inn" . ["∉"])
    ("int" . ["ℤ"])
    ("integral" . ["∫"])
    ("inter" . ["∩"])
    ("intercal" . ["⊺"])
    ("intersection" . ["∩"])
    ("inv" . ["⁻¹"])
    ("io" . ["ι"])
    ("iota" . ["ι"])
    ("iso" . ["≅"])
    ("join" . ["⊔"])
    ("kI" . ["Į"])
    ("ka" . ["κ"])
    ("kappa" . ["κ"])
    ("kelvin" . ["K"])
    ("khei" . ["ϧ"])
    ("ki" . ["į"])
    ("kip" . ["₭"])
    ("koppa" . ["ϟ"])
    ("l" . ["←"])
    ("l-" . ["←"])
    ("l--" . ["⟵"])
    ("l-2" . ["⇇"])
    ("l->" . ["↢"])
    ("l-n" . ["↚"])
    ("l-r-" . ["⇆"])
    ("l-|" . ["↤"])
    ("l1" . ["→₁"])
    ("l1simplefunc" . ["→₁ₛ"])
    ("l=" . ["⇐"])
    ("l==" . ["⇚"])
    ("l=n" . ["⇍"])
    ("la" . ["λ"])
    ("lam" . ["λ"])
    ("lambda" . ["λ"])
    ("lamda" . ["λ"])
    ("langle" . ["⟨"])
    ("lari" . ["₾"])
    ("lbag" . ["⟅"])
    ("lceil" . ["⌈"])
    ("ldata" . ["《"])
    ("ldots" . ["…"])
    ("ldq" . ["“"])
    ("le" . ["≤"])
    ("leadsto" . ["↝"])
    ("leftarrow" . ["←"])
    ("leftarrowtail" . ["↢"])
    ("leftharpoondown" . ["↽"])
    ("leftharpoonup" . ["↼"])
    ("leftleftarrows" . ["⇇"])
    ("leftrightarrow" . ["↔"])
    ("leftrightarrows" . ["⇆"])
    ("leftrightharpoons" . ["⇋"])
    ("leftrightsquigarrow" . ["↭"])
    ("leftthreetimes" . ["⋋"])
    ("len" . ["≰"])
    ("leq" . ["≤"])
    ("leqn" . ["≰"])
    ("leqq" . ["≦"])
    ("leqslant" . ["≤"])
    ("lessapprox" . ["≲"])
    ("lessdot" . ["⋖"])
    ("lesseqgtr" . ["⋚"])
    ("lesseqqgtr" . ["⋚"])
    ("lessgtr" . ["≶"])
    ("lesssim" . ["≲"])
    ("lf" . ["⧏"])
    ("lfloor" . ["⌊"])
    ("lhd" . ["◁"])
    ("liel" . ["⁅"])
    ("lier" . ["⁆"])
    ("linearmap" . ["→ₗ"])
    ("lira" . ["₤"])
    ("ll" . ["≪"])
    ("ll-" . ["↞"])
    ("llbracket" . ["〚"])
    ("llcorner" . ["⌞"])
    ("lnapprox" . ["⋦"])
    ("lneq" . ["≨"])
    ("lneqq" . ["≨"])
    ("lnot" . ["¬"])
    ("lnsim" . ["⋦"])
    ("longleftarrow" . ["⟵"])
    ("longleftrightarrow" . ["⟷"])
    ("longrightarrow" . ["⟶"])
    ("looparrowleft" . ["↫"])
    ("looparrowright" . ["↬"])
    ("lozenge" . ["✧"])
    ("lq" . ["‘"])
    ("lr" . ["↔"])
    ("lr-" . ["↔"])
    ("lr--" . ["⟷"])
    ("lr-n" . ["↮"])
    ("lr=" . ["⇔"])
    ("lr=n" . ["⇎"])
    ("lrcorner" . ["⌟"])
    ("lr~" . ["↭"])
    ("ltimes" . ["⋉"])
    ("lub" . ["⊔"])
    ("lvertneqq" . ["≨"])
    ("l~" . ["↜"])
    ("m" . ["μ"])
    ("m=" . ["≞"])
    ("male" . ["♂"])
    ("maltese" . ["✠"])
    ("manat" . ["₼"])
    ("mapsto" . ["↦"])
    ("mathscr{I}" . ["ℐ"])
    ("measuredangle" . ["∡"])
    ("meet" . ["⊓"])
    ("mem" . ["∈"])
    ("member" . ["∈"])
    ("mho" . ["℧"])
    ("micro" . ["µ"])
    ("mid" . ["∣"])
    ("mill" . ["₥"])
    ("minus" . ["−"])
    ("models" . ["⊧"])
    ("mop" . ["ᵐᵒᵖ"])
    ("mp" . ["∓"])
    ("mu" . ["μ"])
    ("multimap" . ["⊸"])
    ("multiplication" . ["×"])
    ("n" . ["¬"])
    ("nLeftarrow" . ["⇍"])
    ("nLeftrightarrow" . ["⇎"])
    ("nRightarrow" . ["⇏"])
    ("nVDash" . ["⊯"])
    ("nVdash" . ["⊮"])
    ("nabla" . ["∇"])
    ("naira" . ["₦"])
    ("napprox" . ["≉"])
    ("nat" . ["ℕ"])
    ("nat_trans" . ["⟹"])
    ("nattrans" . ["⟹"])
    ("natural" . ["♮"])
    ("nbhds" . ["𝓝"])
    ("ncong" . ["≇"])
    ("ne" . ["≠"])
    ("nearrow" . ["↗"])
    ("neg" . ["¬"])
    ("neq" . ["≠"])
    ("nequiv" . ["≢"])
    ("nexists" . ["∄"])
    ("ngeq" . ["≱"])
    ("ngeqq" . ["≱"])
    ("ngeqslant" . ["≱"])
    ("ngtr" . ["≯"])
    ("nhds" . ["𝓝"])
    ("ni" . ["∋"])
    ("nin" . ["∉"])
    ("nleftarrow" . ["↚"])
    ("nleftrightarrow" . ["↮"])
    ("nleq" . ["≰"])
    ("nleqq" . ["≰"])
    ("nleqslant" . ["≰"])
    ("nless" . ["≮"])
    ("nmid" . ["∤"])
    ("nni" . ["∌"])
    ("nnreal" . ["ℝ≥0"])
    ("nomisma" . ["𐆎"])
    ("not" . ["¬"])
    ("note" . ["♩"])
    ("notin" . ["∉"])
    ("nparallel" . ["∦"])
    ("nprec" . ["⊀"])
    ("npreceq" . ["⋠"])
    ("nrightarrow" . ["↛"])
    ("nshortmid" . ["∤"])
    ("nsim" . ["≁"])
    ("nsimeq" . ["≄"])
    ("nsubset" . ["⊄"])
    ("nsubseteq" . ["⊈"])
    ("nsubseteqq" . ["⊈"])
    ("nsucc" . ["⊁"])
    ("nsucceq" . ["⋡"])
    ("nsupset" . ["⊅"])
    ("nsupseteq" . ["⊉"])
    ("nsupseteqq" . ["⊉"])
    ("ntriangleleft" . ["⋪"])
    ("ntrianglelefteq" . ["⋬"])
    ("ntriangleright" . ["⋫"])
    ("ntrianglerighteq" . ["⋭"])
    ("nu" . ["ν"])
    ("numero" . ["№"])
    ("nvDash" . ["⊭"])
    ("nvdash" . ["⊬"])
    ("nwarrow" . ["↖"])
    ("o" . ["∘"])
    ("o*" . ["∘*"])
    ("o+" . ["⊕"])
    ("o-" . ["⊝"])
    ("o--" . ["⊖"])
    ("o." . ["⊙"])
    ("o/" . ["⊘"])
    ("o=" . ["⊜"])
    ("octagonal" . ["🛑"])
    ("od" . ["ᵒᵈ"])
    ("odot" . ["⊙"])
    ("oe" . ["œ"])
    ("ohm" . ["Ω"])
    ("oint" . ["∮"])
    ("om" . ["ω"])
    ("omega" . ["ω"])
    ("omicron" . ["ο"])
    ("ominus" . ["⊖"])
    ("oo" . ["⊚"])
    ("op" . ["ᵒᵖ"])
    ("oplus" . ["⊕"])
    ("or" . ["∨"])
    ("or=" . ["≚"])
    ("ordfeminine" . ["ª"])
    ("ordmasculine" . ["º"])
    ("oslash" . ["⊘"])
    ("otimes" . ["⊗"])
    ("ounce" . ["℥"])
    ("ox" . ["⊗"])
    ("p" . ["Π"])
    ("pa" . ["▰"])
    ("pab" . ["▰"])
    ("paragraph" . ["¶"])
    ("parallel" . ["∥"])
    ("partial" . ["∂"])
    ("partnership" . ["㉐"])
    ("paw" . ["▱"])
    ("per" . ["⅌"])
    ("permil" . ["‰"])
    ("perp" . ["⟂"])
    ("peseta" . ["₧"])
    ("peso" . ["₱"])
    ("ph" . ["φ"])
    ("phi" . ["φ"])
    ("pi" . ["π"])
    ("pilcrow" . ["¶"])
    ("pitchfork" . ["⋔"])
    ("pm" . ["±"])
    ("pound" . ["£"])
    ("pounds" . ["£"])
    ("powerset" . ["𝒫"])
    ("pr" . ["↣"])
    ("prec" . ["≺"])
    ("precapprox" . ["≾"])
    ("preceq" . ["≼"])
    ("precnapprox" . ["⋨"])
    ("precnsim" . ["⋨"])
    ("precsim" . ["≾"])
    ("preim" . ["⁻¹'"])
    ("preimage" . ["⁻¹'"])
    ("prime" . ["′"])
    ("prod" . ["∏"])
    ("prohibited" . ["🛇"])
    ("propto" . ["∝"])
    ("ps" . ["ψ"])
    ("psi" . ["ψ"])
    ("qed" . ["∎"])
    ("quad" . [" "])
    ("quot" . ["⧸"])
    ("r" . ["→"])
    ("r-" . ["→"])
    ("r--" . ["⟶"])
    ("r-2" . ["⇉"])
    ("r-3" . ["⇶"])
    ("r->" . ["↣"])
    ("r-l-" . ["⇄"])
    ("r-n" . ["↛"])
    ("r-o" . ["⊸"])
    ("r-|" . ["↦"])
    ("r0" . ["→₀"])
    ("r1" . ["→₁"])
    ("r1s" . ["→₁ₛ"])
    ("r=" . ["⇒"])
    ("r==" . ["⇛"])
    ("r=n" . ["⇏"])
    ("r^b" . ["→ᵇ"])
    ("r_0" . ["→₀"])
    ("r_1" . ["→₁"])
    ("r_1s" . ["→₁ₛ"])
    ("r_a" . ["→ₐ"])
    ("r_l" . ["→ₗ"])
    ("r_m" . ["→ₘ"])
    ("r_p" . ["→ₚ"])
    ("r_s" . ["→ₛ"])
    ("ra" . ["→ₐ"])
    ("radioactive" . ["☢"])
    ("rangle" . ["⟩"])
    ("rat" . ["ℚ"])
    ("rb" . ["→ᵇ"])
    ("rbag" . ["⟆"])
    ("rceil" . ["⌉"])
    ("rdata" . ["》"])
    ("rdq" . ["”"])
    ("re" . ["▬"])
    ("real" . ["ℝ"])
    ("reb" . ["▬"])
    ("registered" . ["®"])
    ("rew" . ["▭"])
    ("rfloor" . ["⌋"])
    ("rh" . ["ρ"])
    ("rhd" . ["▷"])
    ("rho" . ["ρ"])
    ("rial" . ["﷼"])
    ("rightangle" . ["∟"])
    ("rightarrow" . ["→"])
    ("rightarrowtail" . ["↣"])
    ("rightharpoondown" . ["⇁"])
    ("rightharpoonup" . ["⇀"])
    ("rightleftarrows" . ["⇄"])
    ("rightleftharpoons" . ["⇌"])
    ("rightrightarrows" . ["⇉"])
    ("rightthreetimes" . ["⋌"])
    ("risingdotseq" . ["≓"])
    ("rl" . ["→ₗ"])
    ("rm" . ["→ₘ"])
    ("root" . ["√"])
    ("rp" . ["→ₚ"])
    ("rq" . ["’"])
    ("rr-" . ["↠"])
    ("rs" . ["→ₛ"])
    ("rtimes" . ["⋊"])
    ("ruble" . ["₽"])
    ("rupee" . ["₨"])
    ("r~" . ["↝"])
    ("sampi" . ["ϡ"])
    ("san" . ["ϻ"])
    ("sb0" . ["𝟬"])
    ("sb1" . ["𝟭"])
    ("sb2" . ["𝟮"])
    ("sb3" . ["𝟯"])
    ("sb4" . ["𝟰"])
    ("sb5" . ["𝟱"])
    ("sb6" . ["𝟲"])
    ("sb7" . ["𝟳"])
    ("sb8" . ["𝟴"])
    ("sb9" . ["𝟵"])
    ("sbs" . ["﹨"])
    ("searrow" . ["↘"])
    ("section" . ["§"])
    ("setminus" . ["∖"])
    ("sharp" . ["♯"])
    ("shei" . ["ϣ"])
    ("shima" . ["ϭ"])
    ("sho" . ["ϸ"])
    ("shortmid" . ["∣"])
    ("si" . ["σ"])
    ("sigma" . ["σ"])
    ("sigmaobj" . ["∐"])
    ("sim" . ["∼"])
    ("simeq" . ["≃"])
    ("simplefunc" . ["→ₛ"])
    ("smallamalg" . ["∐"])
    ("smallsetminus" . ["∖"])
    ("smallsmile" . ["⌣"])
    ("smile" . ["⌣"])
    ("smul" . ["•"])
    ("spadesuit" . ["♠"])
    ("specializes" . ["⤳"])
    ("spesmilo" . ["₷"])
    ("sphericalangle" . ["∢"])
    ("sq" . ["◾"])
    ("sq." . ["▣"])
    ("sqb" . ["■"])
    ("sqcap" . ["⊓"])
    ("sqcup" . ["⊔"])
    ("sqo" . ["▢"])
    ("sqrt" . ["√"])
    ("sqsubset" . ["⊏"])
    ("sqsubseteq" . ["⊑"])
    ("sqsupset" . ["⊐"])
    ("sqsupseteq" . ["⊒"])
    ("square" . ["□"])
    ("squb" . ["⊑"])
    ("squbn" . ["⋢"])
    ("squigarrowright" . ["⇝"])
    ("squp" . ["⊒"])
    ("squpn" . ["⋣"])
    ("sqw" . ["□"])
    ("ss" . ["⊆"])
    ("ssqub" . ["⊏"])
    ("ssqup" . ["⊐"])
    ("ssub" . ["⊂"])
    ("ssubn" . ["⊄"])
    ("ssup" . ["⊃"])
    ("ssupn" . ["⊅"])
    ("st" . ["⋆"])
    ("st12" . ["✹"])
    ("st4" . ["✦"])
    ("st6" . ["✶"])
    ("st8" . ["✴"])
    ("star" . ["⋆"])
    ("stigma" . ["ϛ"])
    ("straightphi" . ["φ"])
    ("sub" . ["⊆"])
    ("subn" . ["⊈"])
    ("subset" . ["⊂"])
    ("subseteq" . ["⊆"])
    ("subseteqq" . ["⊆"])
    ("subsetneq" . ["⊊"])
    ("subsetneqq" . ["⊊"])
    ("succ" . ["≻"])
    ("succapprox" . ["≿"])
    ("succcurlyeq" . ["≽"])
    ("succeq" . ["≽"])
    ("succnapprox" . ["⋩"])
    ("succnsim" . ["⋩"])
    ("succsim" . ["≿"])
    ("sum" . ["∑"])
    ("sup" . ["⊔"])
    ("supn" . ["⊉"])
    ("supr" . ["⨆"])
    ("supset" . ["⊃"])
    ("supseteq" . ["⊇"])
    ("supseteqq" . ["⊇"])
    ("supsetneq" . ["⊋"])
    ("supsetneqq" . ["⊋"])
    ("surd" . ["√"])
    ("surd3" . ["∛"])
    ("surd4" . ["∜"])
    ("swarrow" . ["↙"])
    ("sy" . ["⁻¹"])
    ("t" . ["▸"])
    ("t=" . ["≜"])
    ("ta" . ["τ"])
    ("tau" . ["τ"])
    ("tb" . ["◂"])
    ("telephone" . ["℡"])
    ("tenge" . ["₸"])
    ("textbaht" . ["฿"])
    ("textcircledP" . ["℗"])
    ("textcolonmonetary" . ["₡"])
    ("textdied" . ["✝"])
    ("textdiscount" . ["⁒"])
    ("textestimated" . ["℮"])
    ("textfractionsolidus" . ["⁄"])
    ("textinterrobang" . ["‽"])
    ("textlira" . ["₤"])
    ("textlquill" . ["⁅"])
    ("textmu" . ["µ"])
    ("textmusicalnote" . ["♪"])
    ("textnaira" . ["₦"])
    ("textnumero" . ["№"])
    ("textopenbullet" . ["◦"])
    ("textpertenthousand" . ["‱"])
    ("textpeso" . ["₱"])
    ("textrecipe" . ["℞"])
    ("textreferencemark" . ["※"])
    ("textrquill" . ["⁆"])
    ("textwon" . ["₩"])
    ("th" . ["θ"])
    ("therefore" . ["∴"])
    ("theta" . ["θ"])
    ("thickapprox" . ["≈"])
    ("thicksim" . ["∼"])
    ("tie" . ["⁀"])
    ("times" . ["×"])
    ("to" . ["→"])
    ("to0" . ["→₀"])
    ("to1" . ["→₁"])
    ("to1s" . ["→₁ₛ"])
    ("to^b" . ["→ᵇ"])
    ("to_0" . ["→₀"])
    ("to_1" . ["→₁"])
    ("to_1s" . ["→₁ₛ"])
    ("to_a" . ["→ₐ"])
    ("to_l" . ["→ₗ"])
    ("to_m" . ["→ₘ"])
    ("to_p" . ["→ₚ"])
    ("to_s" . ["→ₛ"])
    ("toa" . ["→ₐ"])
    ("tob" . ["→ᵇ"])
    ("tol" . ["→ₗ"])
    ("tom" . ["→ₘ"])
    ("top" . ["⊤"])
    ("tos" . ["→ₛ"])
    ("tr" . ["⬝"])
    ("trans" . ["▹"])
    ("transport" . ["▹"])
    ("triangle" . ["▵"])
    ("triangledown" . ["▿"])
    ("triangleleft" . ["◃"])
    ("trianglelefteq" . ["⊴"])
    ("triangleq" . ["≜"])
    ("triangleright" . ["▹"])
    ("trianglerighteq" . ["⊵"])
    ("tugrik" . ["₮"])
    ("tw" . ["◃"])
    ("twoheadleftarrow" . ["↞"])
    ("twoheadrightarrow" . ["↠"])
    ("u" . ["↑"])
    ("u+" . ["⊎"])
    ("u-" . ["↑"])
    ("u-2" . ["⇈"])
    ("u-d-" . ["⇅"])
    ("u-|" . ["↥"])
    ("u." . ["⊍"])
    ("u=" . ["⇑"])
    ("u==" . ["⟰"])
    ("ud" . ["↕"])
    ("ud-" . ["↕"])
    ("ud-|" . ["↨"])
    ("ud=" . ["⇕"])
    ("ul" . ["↖"])
    ("ul-" . ["↖"])
    ("ul=" . ["⇖"])
    ("ulcorner" . ["⌜"])
    ("un" . ["∪"])
    ("uncertainty" . ["⯑"])
    ("undertie" . ["‿"])
    ("union" . ["∪"])
    ("uparrow" . ["↑"])
    ("updownarrow" . ["↕"])
    ("upleftharpoon" . ["↿"])
    ("uplus" . ["⊎"])
    ("uprightharpoon" . ["↾"])
    ("upsilon" . ["υ"])
    ("upuparrows" . ["⇈"])
    ("ur" . ["↗"])
    ("ur-" . ["↗"])
    ("ur=" . ["⇗"])
    ("urcorner" . ["⌝"])
    ("uu-" . ["↟"])
    ("v" . ["∨"])
    ("vC" . ["Č"])
    ("vD" . ["Ď"])
    ("vDash" . ["⊨"])
    ("vE" . ["Ě"])
    ("varbeta" . ["ϐ"])
    ("varkai" . ["ϗ"])
    ("varkappa" . ["ϰ"])
    ("varphi" . ["ϕ"])
    ("varpi" . ["ϖ"])
    ("varprime" . ["′"])
    ("varpropto" . ["∝"])
    ("varrho" . ["ϱ"])
    ("varsigma" . ["ς"])
    ("vartheta" . ["ϑ"])
    ("vartriangleleft" . ["⊲"])
    ("vartriangleright" . ["⊳"])
    ("vc" . ["č"])
    ("vd" . ["ď"])
    ("vdash" . ["⊢"])
    ("vdots" . ["⋮"])
    ("ve" . ["ě"])
    ("vectorproduct" . ["⨯"])
    ("vee" . ["∨"])
    ("veebar" . ["⊻"])
    ("vsi" . ["ς"])
    ("warning" . ["⚠"])
    ("wcovby" . ["⩿"])
    ("wcovers" . ["⩿"])
    ("wedge" . ["∧"])
    ("won" . ["₩"])
    ("wp" . ["℘"])
    ("wr" . ["≀"])
    ("x" . ["×"])
    ("xf" . ["×ᶠ"])
    ("xi" . ["ξ"])
    ("yen" . ["¥"])
    ("ze" . ["ζ"])
    ("zeta" . ["ζ"])
    ("zsqrtd" . ["ℤ√"])
    ("{{" . ["⦃"])
    ("|" . ["∣"])
    ("|-" . ["⊢"])
    ("|-n" . ["⊬"])
    ("|=" . ["⊨"])
    ("|=n" . ["⊭"])
    ("|n" . ["∤"])
    ("||" . ["‖"])
    ("||-" . ["⊩"])
    ("||-n" . ["⊮"])
    ("||=" . ["⊫"])
    ("||=n" . ["⊯"])
    ("|||-" . ["⊪"])
    ("}}" . ["⦄"])
    ("~" . ["∼"])
    ("~-" . ["≃"])
    ("~-n" . ["≄"])
    ("~=" . ["≅"])
    ("~=n" . ["≇"])
    ("~>" . ["⤳"])
    ("~A" . ["Ã"])
    ("~N" . ["Ñ"])
    ("~O" . ["Õ"])
    ("~a" . ["ã"])
    ("~n" . ["≁"])
    ("~o" . ["õ"])
    ("~{n}" . ["ñ"])
    ("~~" . ["≈"])
    ("~~-" . ["≊"])
    ("~~n" . ["≉"])
    ("~~~" . ["≋"]))
  "List of translations.")

(defun lean4-input-setup ()
  "Set up the Lean input method.

Use customisable variables and parent input methods to setup Lean
input method."
  ;; Create (or reset) the input method.
  (with-temp-buffer
    (quail-define-package
     "Lean" "UTF-8" "∏" t ;; guidance
     "Lean input method.

The purpose of this input method is to edit Lean programs, but since
it is highly customisable it can be made useful for other tasks as
well."
     nil nil nil nil nil nil t)) ;; maximum-shortest

  (lean4-input-add-translations
   (mapcar (lambda (tr) (cons (car tr) (vconcat (cdr tr))))
           lean4-input-user-translations))
  (lean4-input-add-translations lean4-input-translations)
  (dolist (def lean4-input-inherit)
    (lean4-input-inherit-package (car def)
                                 (eval (cdr def)))))

(defun lean4-input-incorporate-changed-setting (sym val)
  "Update the Lean input method.
Set SYM default value to VAL, then call `lean4-input-setup'.
Suitable for use in the :set field of `defcustom'."
  (set-default sym val)
  (lean4-input-setup))

;; Set up the input method.

(cl-eval-when (load eval)
  (lean4-input-setup))

(defun lean4-input-export-translations ()
  "Export the current translations in a javascript format.

Print (input, output) pairs in Javascript format to the buffer
*lean4-translations*.  The output can be copy-pasted to
leanprover.github.io/tutorial/js/input-method.js"
  (interactive)
  (with-current-buffer
      (get-buffer-create "*lean4-translations*")
    (let ((exclude-list '("\\newline")))
      (insert "var corrections = {")
      (dolist
          (translation
           (seq-filter
            (lambda (tn)
              (not (member (car tn) exclude-list)))
            (lean4-input-get-translations "Lean")))
        (let* ((input (substring (car translation) 1))
               (outputs (cdr translation)))
          (insert (format "%s:\"" (prin1-to-string input)))
          (cond ((vectorp outputs)
                 (insert (elt outputs 0)))
                (t (insert-char outputs)))
          (insert (format "\",\n"))))
      (insert "};"))))

(defun lean4-input-export-translations-to-stdout ()
  "Print current translations to stdout."
  (lean4-input-export-translations)
  (with-current-buffer "*lean4-translations*"
    (princ (buffer-string))))

(provide 'lean4-input)

;;; lean4-input.el ends here
