#+title: BROKEN – EXPERIMENTAL – WORK-IN-PROGRESS
#+OPTIONS: toc:nil

*THIS PACKAGE IS BROKEN.  IT DOES NOT WORK!  DO NOT USE IT.*

* Installation

1. [[https://lean-lang.org/lean4/doc/setup.html][Install Lean (version 4)]].
2. Install Nael.
   1. With Git, clone Nael repository to local disk.
   2. In =init.el=, add path of local clone to ~load-path~
      variable.
3. Configure Nael in =init.el=:

#+begin_src elisp
(require 'nael)

(add-to-list 'project-vc-extra-root-markers "lakefile.lean")

(add-hook 'nael-mode-hook #'eglot-ensure)
#+end_src

* About

** History

1. Original:
   https://github.com/leanprover-community/lean4-mode
2. Switched from =lsp-mode= to =eglot=:
    https://github.com/bustercopley/lean4-mode
3. This repository further diverges from the original in an
   opinionated way.

** Roadmap

(This is section lists future plans only. It does not list past
accomplishments.)

Maintenance:

- Remove the JSON file for abbreviations. (WIP)
- Add =lakefile= to ~project-vc-extra-root-markers~ or so. (WIP)
- Rely on =project.el= rather than reimplementing some of its
  features.
- Evaluate if the =(cl-defmethod eglot-...)= are needed.
- Rework indentation (=lean4-eri.el=).

Features:

- Fix =nael-info=, i.e. =*Nael Goal*= buffer.  (It does not work
  right now.  I guess, I broke it.)
- Support fontification via semantic tokens from the language server,
  based on [[https://codeberg.org/eownerdead/eglot-semantic-tokens][this]] or [[https://codeberg.org/harald/eglot-semtok][this]] package, or even help the former being [[https://github.com/joaotavora/eglot/pull/839][merged]]
  into Eglot.

** License

The original =nael-mode= is licensed under Apache-2.0. Additions and
modifications made in this repository are licensed under GNU General
Public License version 3 or later. (Yes, these licenses are compatible
in this way.) Thus this repository contains code under both licenses.
Since GPLv3+ is stricter than Apache2, you can simply treat the source
code as a whole as if it were licensed under GPLv3+.
